'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('Districts', [
            { district_id: 1, name: 'Quận Ba Đình', type: 'Quận', province_id: 1 },
            { district_id: 2, name: 'Quận Hoàn Kiếm', type: 'Quận', province_id: 1 },
            { district_id: 3, name: 'Quận Tây Hồ', type: 'Quận', province_id: 1 },
            { district_id: 4, name: 'Quận Long Biên', type: 'Quận', province_id: 1 },
            { district_id: 5, name: 'Quận Cầu Giấy', type: 'Quận', province_id: 1 },
            { district_id: 6, name: 'Quận Đống Đa', type: 'Quận', province_id: 1 },
            { district_id: 7, name: 'Quận Hai Bà Trưng', type: 'Quận', province_id: 1 },
            { district_id: 8, name: 'Quận Hoàng Mai', type: 'Quận', province_id: 1 },
            { district_id: 9, name: 'Quận Thanh Xuân', type: 'Quận', province_id: 1 },
            { district_id: 10, name: 'Huyện Sóc Sơn', type: 'Huyện', province_id: 1 },
            { district_id: 11, name: 'Huyện Đông Anh', type: 'Huyện', province_id: 1 },
            { district_id: 18, name: 'Huyện Gia Lâm', type: 'Huyện', province_id: 1 },
            { district_id: 19, name: 'Quận Nam Từ Liêm', type: 'Quận', province_id: 1 },
            { district_id: 20, name: 'Huyện Thanh Trì', type: 'Huyện', province_id: 1 },
            { district_id: 21, name: 'Quận Bắc Từ Liêm', type: 'Quận', province_id: 1 },
            { district_id: 24, name: 'Thành phố Hà Giang', type: 'Thành phố', province_id: 2 },
            { district_id: 26, name: 'Huyện Đồng Văn', type: 'Huyện', province_id: 2 },
            { district_id: 27, name: 'Huyện Mèo Vạc', type: 'Huyện', province_id: 2 },
            { district_id: 28, name: 'Huyện Yên Minh', type: 'Huyện', province_id: 2 },
            { district_id: 29, name: 'Huyện Quản Bạ', type: 'Huyện', province_id: 2 },
            { district_id: 30, name: 'Huyện Vị Xuyên', type: 'Huyện', province_id: 2 },
            { district_id: 31, name: 'Huyện Bắc Mê', type: 'Huyện', province_id: 2 },
            { district_id: 32, name: 'Huyện Hoàng Su Phì', type: 'Huyện', province_id: 2 },
            { district_id: 33, name: 'Huyện Xín Mần', type: 'Huyện', province_id: 2 },
            { district_id: 34, name: 'Huyện Bắc Quang', type: 'Huyện', province_id: 2 },
            { district_id: 35, name: 'Huyện Quang Bình', type: 'Huyện', province_id: 2 },
            { district_id: 40, name: 'Thành phố Cao Bằng', type: 'Thành phố', province_id: 4 },
            { district_id: 42, name: 'Huyện Bảo Lâm', type: 'Huyện', province_id: 4 },
            { district_id: 43, name: 'Huyện Bảo Lạc', type: 'Huyện', province_id: 4 },
            { district_id: 44, name: 'Huyện Thông Nông', type: 'Huyện', province_id: 4 },
            { district_id: 45, name: 'Huyện Hà Quảng', type: 'Huyện', province_id: 4 },
            { district_id: 46, name: 'Huyện Trà Lĩnh', type: 'Huyện', province_id: 4 },
            { district_id: 47, name: 'Huyện Trùng Khánh', type: 'Huyện', province_id: 4 },
            { district_id: 48, name: 'Huyện Hạ Lang', type: 'Huyện', province_id: 4 },
            { district_id: 49, name: 'Huyện Quảng Uyên', type: 'Huyện', province_id: 4 },
            { district_id: 50, name: 'Huyện Phục Hoà', type: 'Huyện', province_id: 4 },
            { district_id: 51, name: 'Huyện Hoà An', type: 'Huyện', province_id: 4 },
            { district_id: 52, name: 'Huyện Nguyên Bình', type: 'Huyện', province_id: 4 },
            { district_id: 53, name: 'Huyện Thạch An', type: 'Huyện', province_id: 4 },
            { district_id: 58, name: 'Thành Phố Bắc Kạn', type: 'Thành phố', province_id: 6 },
            { district_id: 60, name: 'Huyện Pác Nặm', type: 'Huyện', province_id: 6 },
            { district_id: 61, name: 'Huyện Ba Bể', type: 'Huyện', province_id: 6 },
            { district_id: 62, name: 'Huyện Ngân Sơn', type: 'Huyện', province_id: 6 },
            { district_id: 63, name: 'Huyện Bạch Thông', type: 'Huyện', province_id: 6 },
            { district_id: 64, name: 'Huyện Chợ Đồn', type: 'Huyện', province_id: 6 },
            { district_id: 65, name: 'Huyện Chợ Mới', type: 'Huyện', province_id: 6 },
            { district_id: 66, name: 'Huyện Na Rì', type: 'Huyện', province_id: 6 },
            {
                district_id: 70,
                name: 'Thành phố Tuyên Quang',
                type: 'Thành phố',
                province_id: 8,
            },
            { district_id: 71, name: 'Huyện Lâm Bình', type: 'Huyện', province_id: 8 },
            { district_id: 72, name: 'Huyện Nà Hang', type: 'Huyện', province_id: 8 },
            { district_id: 73, name: 'Huyện Chiêm Hóa', type: 'Huyện', province_id: 8 },
            { district_id: 74, name: 'Huyện Hàm Yên', type: 'Huyện', province_id: 8 },
            { district_id: 75, name: 'Huyện Yên Sơn', type: 'Huyện', province_id: 8 },
            { district_id: 76, name: 'Huyện Sơn Dương', type: 'Huyện', province_id: 8 },
            { district_id: 80, name: 'Thành phố Lào Cai', type: 'Thành phố', province_id: 10 },
            { district_id: 82, name: 'Huyện Bát Xát', type: 'Huyện', province_id: 10 },
            { district_id: 83, name: 'Huyện Mường Khương', type: 'Huyện', province_id: 10 },
            { district_id: 84, name: 'Huyện Si Ma Cai', type: 'Huyện', province_id: 10 },
            { district_id: 85, name: 'Huyện Bắc Hà', type: 'Huyện', province_id: 10 },
            { district_id: 86, name: 'Huyện Bảo Thắng', type: 'Huyện', province_id: 10 },
            { district_id: 87, name: 'Huyện Bảo Yên', type: 'Huyện', province_id: 10 },
            { district_id: 88, name: 'Huyện Sa Pa', type: 'Huyện', province_id: 10 },
            { district_id: 89, name: 'Huyện Văn Bàn', type: 'Huyện', province_id: 10 },
            {
                district_id: 94,
                name: 'Thành phố Điện Biên Phủ',
                type: 'Thành phố',
                province_id: 11,
            },
            { district_id: 95, name: 'Thị Xã Mường Lay', type: 'Thị xã', province_id: 11 },
            { district_id: 96, name: 'Huyện Mường Nhé', type: 'Huyện', province_id: 11 },
            { district_id: 97, name: 'Huyện Mường Chà', type: 'Huyện', province_id: 11 },
            { district_id: 98, name: 'Huyện Tủa Chùa', type: 'Huyện', province_id: 11 },
            { district_id: 99, name: 'Huyện Tuần Giáo', type: 'Huyện', province_id: 11 },
            { district_id: 100, name: 'Huyện Điện Biên', type: 'Huyện', province_id: 11 },
            { district_id: 101, name: 'Huyện Điện Biên Đông', type: 'Huyện', province_id: 11 },
            { district_id: 102, name: 'Huyện Mường Ảng', type: 'Huyện', province_id: 11 },
            { district_id: 103, name: 'Huyện Nậm Pồ', type: 'Huyện', province_id: 11 },
            {
                district_id: 105,
                name: 'Thành phố Lai Châu',
                type: 'Thành phố',
                province_id: 12,
            },
            { district_id: 106, name: 'Huyện Tam Đường', type: 'Huyện', province_id: 12 },
            { district_id: 107, name: 'Huyện Mường Tè', type: 'Huyện', province_id: 12 },
            { district_id: 108, name: 'Huyện Sìn Hồ', type: 'Huyện', province_id: 12 },
            { district_id: 109, name: 'Huyện Phong Thổ', type: 'Huyện', province_id: 12 },
            { district_id: 110, name: 'Huyện Than Uyên', type: 'Huyện', province_id: 12 },
            { district_id: 111, name: 'Huyện Tân Uyên', type: 'Huyện', province_id: 12 },
            { district_id: 112, name: 'Huyện Nậm Nhùn', type: 'Huyện', province_id: 12 },
            { district_id: 116, name: 'Thành phố Sơn La', type: 'Thành phố', province_id: 14 },
            { district_id: 118, name: 'Huyện Quỳnh Nhai', type: 'Huyện', province_id: 14 },
            { district_id: 119, name: 'Huyện Thuận Châu', type: 'Huyện', province_id: 14 },
            { district_id: 120, name: 'Huyện Mường La', type: 'Huyện', province_id: 14 },
            { district_id: 121, name: 'Huyện Bắc Yên', type: 'Huyện', province_id: 14 },
            { district_id: 122, name: 'Huyện Phù Yên', type: 'Huyện', province_id: 14 },
            { district_id: 123, name: 'Huyện Mộc Châu', type: 'Huyện', province_id: 14 },
            { district_id: 124, name: 'Huyện Yên Châu', type: 'Huyện', province_id: 14 },
            { district_id: 125, name: 'Huyện Mai Sơn', type: 'Huyện', province_id: 14 },
            { district_id: 126, name: 'Huyện Sông Mã', type: 'Huyện', province_id: 14 },
            { district_id: 127, name: 'Huyện Sốp Cộp', type: 'Huyện', province_id: 14 },
            { district_id: 128, name: 'Huyện Vân Hồ', type: 'Huyện', province_id: 14 },
            {
                district_id: 132,
                name: 'Thành phố Yên Bái',
                type: 'Thành phố',
                province_id: 15,
            },
            { district_id: 133, name: 'Thị xã Nghĩa Lộ', type: 'Thị xã', province_id: 15 },
            { district_id: 135, name: 'Huyện Lục Yên', type: 'Huyện', province_id: 15 },
            { district_id: 136, name: 'Huyện Văn Yên', type: 'Huyện', province_id: 15 },
            { district_id: 137, name: 'Huyện Mù Căng Chải', type: 'Huyện', province_id: 15 },
            { district_id: 138, name: 'Huyện Trấn Yên', type: 'Huyện', province_id: 15 },
            { district_id: 139, name: 'Huyện Trạm Tấu', type: 'Huyện', province_id: 15 },
            { district_id: 140, name: 'Huyện Văn Chấn', type: 'Huyện', province_id: 15 },
            { district_id: 141, name: 'Huyện Yên Bình', type: 'Huyện', province_id: 15 },
            {
                district_id: 148,
                name: 'Thành phố Hòa Bình',
                type: 'Thành phố',
                province_id: 17,
            },
            { district_id: 150, name: 'Huyện Đà Bắc', type: 'Huyện', province_id: 17 },
            { district_id: 152, name: 'Huyện Lương Sơn', type: 'Huyện', province_id: 17 },
            { district_id: 153, name: 'Huyện Kim Bôi', type: 'Huyện', province_id: 17 },
            { district_id: 154, name: 'Huyện Cao Phong', type: 'Huyện', province_id: 17 },
            { district_id: 155, name: 'Huyện Tân Lạc', type: 'Huyện', province_id: 17 },
            { district_id: 156, name: 'Huyện Mai Châu', type: 'Huyện', province_id: 17 },
            { district_id: 157, name: 'Huyện Lạc Sơn', type: 'Huyện', province_id: 17 },
            { district_id: 158, name: 'Huyện Yên Thủy', type: 'Huyện', province_id: 17 },
            { district_id: 159, name: 'Huyện Lạc Thủy', type: 'Huyện', province_id: 17 },
            {
                district_id: 164,
                name: 'Thành phố Thái Nguyên',
                type: 'Thành phố',
                province_id: 19,
            },
            {
                district_id: 165,
                name: 'Thành phố Sông Công',
                type: 'Thành phố',
                province_id: 19,
            },
            { district_id: 167, name: 'Huyện Định Hóa', type: 'Huyện', province_id: 19 },
            { district_id: 168, name: 'Huyện Phú Lương', type: 'Huyện', province_id: 19 },
            { district_id: 169, name: 'Huyện Đồng Hỷ', type: 'Huyện', province_id: 19 },
            { district_id: 170, name: 'Huyện Võ Nhai', type: 'Huyện', province_id: 19 },
            { district_id: 171, name: 'Huyện Đại Từ', type: 'Huyện', province_id: 19 },
            { district_id: 172, name: 'Thị xã Phổ Yên', type: 'Thị xã', province_id: 19 },
            { district_id: 173, name: 'Huyện Phú Bình', type: 'Huyện', province_id: 19 },
            {
                district_id: 178,
                name: 'Thành phố Lạng Sơn',
                type: 'Thành phố',
                province_id: 20,
            },
            { district_id: 180, name: 'Huyện Tràng Định', type: 'Huyện', province_id: 20 },
            { district_id: 181, name: 'Huyện Bình Gia', type: 'Huyện', province_id: 20 },
            { district_id: 182, name: 'Huyện Văn Lãng', type: 'Huyện', province_id: 20 },
            { district_id: 183, name: 'Huyện Cao Lộc', type: 'Huyện', province_id: 20 },
            { district_id: 184, name: 'Huyện Văn Quan', type: 'Huyện', province_id: 20 },
            { district_id: 185, name: 'Huyện Bắc Sơn', type: 'Huyện', province_id: 20 },
            { district_id: 186, name: 'Huyện Hữu Lũng', type: 'Huyện', province_id: 20 },
            { district_id: 187, name: 'Huyện Chi Lăng', type: 'Huyện', province_id: 20 },
            { district_id: 188, name: 'Huyện Lộc Bình', type: 'Huyện', province_id: 20 },
            { district_id: 189, name: 'Huyện Đình Lập', type: 'Huyện', province_id: 20 },
            {
                district_id: 193,
                name: 'Thành phố Hạ Long',
                type: 'Thành phố',
                province_id: 22,
            },
            {
                district_id: 194,
                name: 'Thành phố Móng Cái',
                type: 'Thành phố',
                province_id: 22,
            },
            {
                district_id: 195,
                name: 'Thành phố Cẩm Phả',
                type: 'Thành phố',
                province_id: 22,
            },
            {
                district_id: 196,
                name: 'Thành phố Uông Bí',
                type: 'Thành phố',
                province_id: 22,
            },
            { district_id: 198, name: 'Huyện Bình Liêu', type: 'Huyện', province_id: 22 },
            { district_id: 199, name: 'Huyện Tiên Yên', type: 'Huyện', province_id: 22 },
            { district_id: 200, name: 'Huyện Đầm Hà', type: 'Huyện', province_id: 22 },
            { district_id: 201, name: 'Huyện Hải Hà', type: 'Huyện', province_id: 22 },
            { district_id: 202, name: 'Huyện Ba Chẽ', type: 'Huyện', province_id: 22 },
            { district_id: 203, name: 'Huyện Vân Đồn', type: 'Huyện', province_id: 22 },
            { district_id: 204, name: 'Huyện Hoành Bồ', type: 'Huyện', province_id: 22 },
            { district_id: 205, name: 'Thị xã Đông Triều', type: 'Thị xã', province_id: 22 },
            { district_id: 206, name: 'Thị xã Quảng Yên', type: 'Thị xã', province_id: 22 },
            { district_id: 207, name: 'Huyện Cô Tô', type: 'Huyện', province_id: 22 },
            {
                district_id: 213,
                name: 'Thành phố Bắc Giang',
                type: 'Thành phố',
                province_id: 24,
            },
            { district_id: 215, name: 'Huyện Yên Thế', type: 'Huyện', province_id: 24 },
            { district_id: 216, name: 'Huyện Tân Yên', type: 'Huyện', province_id: 24 },
            { district_id: 217, name: 'Huyện Lạng Giang', type: 'Huyện', province_id: 24 },
            { district_id: 218, name: 'Huyện Lục Nam', type: 'Huyện', province_id: 24 },
            { district_id: 219, name: 'Huyện Lục Ngạn', type: 'Huyện', province_id: 24 },
            { district_id: 220, name: 'Huyện Sơn Động', type: 'Huyện', province_id: 24 },
            { district_id: 221, name: 'Huyện Yên Dũng', type: 'Huyện', province_id: 24 },
            { district_id: 222, name: 'Huyện Việt Yên', type: 'Huyện', province_id: 24 },
            { district_id: 223, name: 'Huyện Hiệp Hòa', type: 'Huyện', province_id: 24 },
            {
                district_id: 227,
                name: 'Thành phố Việt Trì',
                type: 'Thành phố',
                province_id: 25,
            },
            { district_id: 228, name: 'Thị xã Phú Thọ', type: 'Thị xã', province_id: 25 },
            { district_id: 230, name: 'Huyện Đoan Hùng', type: 'Huyện', province_id: 25 },
            { district_id: 231, name: 'Huyện Hạ Hoà', type: 'Huyện', province_id: 25 },
            { district_id: 232, name: 'Huyện Thanh Ba', type: 'Huyện', province_id: 25 },
            { district_id: 233, name: 'Huyện Phù Ninh', type: 'Huyện', province_id: 25 },
            { district_id: 234, name: 'Huyện Yên Lập', type: 'Huyện', province_id: 25 },
            { district_id: 235, name: 'Huyện Cẩm Khê', type: 'Huyện', province_id: 25 },
            { district_id: 236, name: 'Huyện Tam Nông', type: 'Huyện', province_id: 25 },
            { district_id: 237, name: 'Huyện Lâm Thao', type: 'Huyện', province_id: 25 },
            { district_id: 238, name: 'Huyện Thanh Sơn', type: 'Huyện', province_id: 25 },
            { district_id: 239, name: 'Huyện Thanh Thuỷ', type: 'Huyện', province_id: 25 },
            { district_id: 240, name: 'Huyện Tân Sơn', type: 'Huyện', province_id: 25 },
            {
                district_id: 243,
                name: 'Thành phố Vĩnh Yên',
                type: 'Thành phố',
                province_id: 26,
            },
            { district_id: 244, name: 'Thị xã Phúc Yên', type: 'Thị xã', province_id: 26 },
            { district_id: 246, name: 'Huyện Lập Thạch', type: 'Huyện', province_id: 26 },
            { district_id: 247, name: 'Huyện Tam Dương', type: 'Huyện', province_id: 26 },
            { district_id: 248, name: 'Huyện Tam Đảo', type: 'Huyện', province_id: 26 },
            { district_id: 249, name: 'Huyện Bình Xuyên', type: 'Huyện', province_id: 26 },
            { district_id: 250, name: 'Huyện Mê Linh', type: 'Huyện', province_id: 1 },
            { district_id: 251, name: 'Huyện Yên Lạc', type: 'Huyện', province_id: 26 },
            { district_id: 252, name: 'Huyện Vĩnh Tường', type: 'Huyện', province_id: 26 },
            { district_id: 253, name: 'Huyện Sông Lô', type: 'Huyện', province_id: 26 },
            {
                district_id: 256,
                name: 'Thành phố Bắc Ninh',
                type: 'Thành phố',
                province_id: 27,
            },
            { district_id: 258, name: 'Huyện Yên Phong', type: 'Huyện', province_id: 27 },
            { district_id: 259, name: 'Huyện Quế Võ', type: 'Huyện', province_id: 27 },
            { district_id: 260, name: 'Huyện Tiên Du', type: 'Huyện', province_id: 27 },
            { district_id: 261, name: 'Thị xã Từ Sơn', type: 'Thị xã', province_id: 27 },
            { district_id: 262, name: 'Huyện Thuận Thành', type: 'Huyện', province_id: 27 },
            { district_id: 263, name: 'Huyện Gia Bình', type: 'Huyện', province_id: 27 },
            { district_id: 264, name: 'Huyện Lương Tài', type: 'Huyện', province_id: 27 },
            { district_id: 268, name: 'Quận Hà Đông', type: 'Quận', province_id: 1 },
            { district_id: 269, name: 'Thị xã Sơn Tây', type: 'Thị xã', province_id: 1 },
            { district_id: 271, name: 'Huyện Ba Vì', type: 'Huyện', province_id: 1 },
            { district_id: 272, name: 'Huyện Phúc Thọ', type: 'Huyện', province_id: 1 },
            { district_id: 273, name: 'Huyện Đan Phượng', type: 'Huyện', province_id: 1 },
            { district_id: 274, name: 'Huyện Hoài Đức', type: 'Huyện', province_id: 1 },
            { district_id: 275, name: 'Huyện Quốc Oai', type: 'Huyện', province_id: 1 },
            { district_id: 276, name: 'Huyện Thạch Thất', type: 'Huyện', province_id: 1 },
            { district_id: 277, name: 'Huyện Chương Mỹ', type: 'Huyện', province_id: 1 },
            { district_id: 278, name: 'Huyện Thanh Oai', type: 'Huyện', province_id: 1 },
            { district_id: 279, name: 'Huyện Thường Tín', type: 'Huyện', province_id: 1 },
            { district_id: 280, name: 'Huyện Phú Xuyên', type: 'Huyện', province_id: 1 },
            { district_id: 281, name: 'Huyện Ứng Hòa', type: 'Huyện', province_id: 1 },
            { district_id: 282, name: 'Huyện Mỹ Đức', type: 'Huyện', province_id: 1 },
            {
                district_id: 288,
                name: 'Thành phố Hải Dương',
                type: 'Thành phố',
                province_id: 30,
            },
            { district_id: 290, name: 'Thị xã Chí Linh', type: 'Thị xã', province_id: 30 },
            { district_id: 291, name: 'Huyện Nam Sách', type: 'Huyện', province_id: 30 },
            { district_id: 292, name: 'Huyện Kinh Môn', type: 'Huyện', province_id: 30 },
            { district_id: 293, name: 'Huyện Kim Thành', type: 'Huyện', province_id: 30 },
            { district_id: 294, name: 'Huyện Thanh Hà', type: 'Huyện', province_id: 30 },
            { district_id: 295, name: 'Huyện Cẩm Giàng', type: 'Huyện', province_id: 30 },
            { district_id: 296, name: 'Huyện Bình Giang', type: 'Huyện', province_id: 30 },
            { district_id: 297, name: 'Huyện Gia Lộc', type: 'Huyện', province_id: 30 },
            { district_id: 298, name: 'Huyện Tứ Kỳ', type: 'Huyện', province_id: 30 },
            { district_id: 299, name: 'Huyện Ninh Giang', type: 'Huyện', province_id: 30 },
            { district_id: 300, name: 'Huyện Thanh Miện', type: 'Huyện', province_id: 30 },
            { district_id: 303, name: 'Quận Hồng Bàng', type: 'Quận', province_id: 31 },
            { district_id: 304, name: 'Quận Ngô Quyền', type: 'Quận', province_id: 31 },
            { district_id: 305, name: 'Quận Lê Chân', type: 'Quận', province_id: 31 },
            { district_id: 306, name: 'Quận Hải An', type: 'Quận', province_id: 31 },
            { district_id: 307, name: 'Quận Kiến An', type: 'Quận', province_id: 31 },
            { district_id: 308, name: 'Quận Đồ Sơn', type: 'Quận', province_id: 31 },
            { district_id: 309, name: 'Quận Dương Kinh', type: 'Quận', province_id: 31 },
            { district_id: 311, name: 'Huyện Thuỷ Nguyên', type: 'Huyện', province_id: 31 },
            { district_id: 312, name: 'Huyện An Dương', type: 'Huyện', province_id: 31 },
            { district_id: 313, name: 'Huyện An Lão', type: 'Huyện', province_id: 31 },
            { district_id: 314, name: 'Huyện Kiến Thuỵ', type: 'Huyện', province_id: 31 },
            { district_id: 315, name: 'Huyện Tiên Lãng', type: 'Huyện', province_id: 31 },
            { district_id: 316, name: 'Huyện Vĩnh Bảo', type: 'Huyện', province_id: 31 },
            { district_id: 317, name: 'Huyện Cát Hải', type: 'Huyện', province_id: 31 },
            { district_id: 318, name: 'Huyện Bạch Long Vĩ', type: 'Huyện', province_id: 31 },
            {
                district_id: 323,
                name: 'Thành phố Hưng Yên',
                type: 'Thành phố',
                province_id: 33,
            },
            { district_id: 325, name: 'Huyện Văn Lâm', type: 'Huyện', province_id: 33 },
            { district_id: 326, name: 'Huyện Văn Giang', type: 'Huyện', province_id: 33 },
            { district_id: 327, name: 'Huyện Yên Mỹ', type: 'Huyện', province_id: 33 },
            { district_id: 328, name: 'Huyện Mỹ Hào', type: 'Huyện', province_id: 33 },
            { district_id: 329, name: 'Huyện Ân Thi', type: 'Huyện', province_id: 33 },
            { district_id: 330, name: 'Huyện Khoái Châu', type: 'Huyện', province_id: 33 },
            { district_id: 331, name: 'Huyện Kim Động', type: 'Huyện', province_id: 33 },
            { district_id: 332, name: 'Huyện Tiên Lữ', type: 'Huyện', province_id: 33 },
            { district_id: 333, name: 'Huyện Phù Cừ', type: 'Huyện', province_id: 33 },
            {
                district_id: 336,
                name: 'Thành phố Thái Bình',
                type: 'Thành phố',
                province_id: 34,
            },
            { district_id: 338, name: 'Huyện Quỳnh Phụ', type: 'Huyện', province_id: 34 },
            { district_id: 339, name: 'Huyện Hưng Hà', type: 'Huyện', province_id: 34 },
            { district_id: 340, name: 'Huyện Đông Hưng', type: 'Huyện', province_id: 34 },
            { district_id: 341, name: 'Huyện Thái Thụy', type: 'Huyện', province_id: 34 },
            { district_id: 342, name: 'Huyện Tiền Hải', type: 'Huyện', province_id: 34 },
            { district_id: 343, name: 'Huyện Kiến Xương', type: 'Huyện', province_id: 34 },
            { district_id: 344, name: 'Huyện Vũ Thư', type: 'Huyện', province_id: 34 },
            { district_id: 347, name: 'Thành phố Phủ Lý', type: 'Thành phố', province_id: 35 },
            { district_id: 349, name: 'Huyện Duy Tiên', type: 'Huyện', province_id: 35 },
            { district_id: 350, name: 'Huyện Kim Bảng', type: 'Huyện', province_id: 35 },
            { district_id: 351, name: 'Huyện Thanh Liêm', type: 'Huyện', province_id: 35 },
            { district_id: 352, name: 'Huyện Bình Lục', type: 'Huyện', province_id: 35 },
            { district_id: 353, name: 'Huyện Lý Nhân', type: 'Huyện', province_id: 35 },
            {
                district_id: 356,
                name: 'Thành phố Nam Định',
                type: 'Thành phố',
                province_id: 36,
            },
            { district_id: 358, name: 'Huyện Mỹ Lộc', type: 'Huyện', province_id: 36 },
            { district_id: 359, name: 'Huyện Vụ Bản', type: 'Huyện', province_id: 36 },
            { district_id: 360, name: 'Huyện Ý Yên', type: 'Huyện', province_id: 36 },
            { district_id: 361, name: 'Huyện Nghĩa Hưng', type: 'Huyện', province_id: 36 },
            { district_id: 362, name: 'Huyện Nam Trực', type: 'Huyện', province_id: 36 },
            { district_id: 363, name: 'Huyện Trực Ninh', type: 'Huyện', province_id: 36 },
            { district_id: 364, name: 'Huyện Xuân Trường', type: 'Huyện', province_id: 36 },
            { district_id: 365, name: 'Huyện Giao Thủy', type: 'Huyện', province_id: 36 },
            { district_id: 366, name: 'Huyện Hải Hậu', type: 'Huyện', province_id: 36 },
            {
                district_id: 369,
                name: 'Thành phố Ninh Bình',
                type: 'Thành phố',
                province_id: 37,
            },
            {
                district_id: 370,
                name: 'Thành phố Tam Điệp',
                type: 'Thành phố',
                province_id: 37,
            },
            { district_id: 372, name: 'Huyện Nho Quan', type: 'Huyện', province_id: 37 },
            { district_id: 373, name: 'Huyện Gia Viễn', type: 'Huyện', province_id: 37 },
            { district_id: 374, name: 'Huyện Hoa Lư', type: 'Huyện', province_id: 37 },
            { district_id: 375, name: 'Huyện Yên Khánh', type: 'Huyện', province_id: 37 },
            { district_id: 376, name: 'Huyện Kim Sơn', type: 'Huyện', province_id: 37 },
            { district_id: 377, name: 'Huyện Yên Mô', type: 'Huyện', province_id: 37 },
            {
                district_id: 380,
                name: 'Thành phố Thanh Hóa',
                type: 'Thành phố',
                province_id: 38,
            },
            { district_id: 381, name: 'Thị xã Bỉm Sơn', type: 'Thị xã', province_id: 38 },
            { district_id: 382, name: 'Thị xã Sầm Sơn', type: 'Thị xã', province_id: 38 },
            { district_id: 384, name: 'Huyện Mường Lát', type: 'Huyện', province_id: 38 },
            { district_id: 385, name: 'Huyện Quan Hóa', type: 'Huyện', province_id: 38 },
            { district_id: 386, name: 'Huyện Bá Thước', type: 'Huyện', province_id: 38 },
            { district_id: 387, name: 'Huyện Quan Sơn', type: 'Huyện', province_id: 38 },
            { district_id: 388, name: 'Huyện Lang Chánh', type: 'Huyện', province_id: 38 },
            { district_id: 389, name: 'Huyện Ngọc Lặc', type: 'Huyện', province_id: 38 },
            { district_id: 390, name: 'Huyện Cẩm Thủy', type: 'Huyện', province_id: 38 },
            { district_id: 391, name: 'Huyện Thạch Thành', type: 'Huyện', province_id: 38 },
            { district_id: 392, name: 'Huyện Hà Trung', type: 'Huyện', province_id: 38 },
            { district_id: 393, name: 'Huyện Vĩnh Lộc', type: 'Huyện', province_id: 38 },
            { district_id: 394, name: 'Huyện Yên Định', type: 'Huyện', province_id: 38 },
            { district_id: 395, name: 'Huyện Thọ Xuân', type: 'Huyện', province_id: 38 },
            { district_id: 396, name: 'Huyện Thường Xuân', type: 'Huyện', province_id: 38 },
            { district_id: 397, name: 'Huyện Triệu Sơn', type: 'Huyện', province_id: 38 },
            { district_id: 398, name: 'Huyện Thiệu Hóa', type: 'Huyện', province_id: 38 },
            { district_id: 399, name: 'Huyện Hoằng Hóa', type: 'Huyện', province_id: 38 },
            { district_id: 400, name: 'Huyện Hậu Lộc', type: 'Huyện', province_id: 38 },
            { district_id: 401, name: 'Huyện Nga Sơn', type: 'Huyện', province_id: 38 },
            { district_id: 402, name: 'Huyện Như Xuân', type: 'Huyện', province_id: 38 },
            { district_id: 403, name: 'Huyện Như Thanh', type: 'Huyện', province_id: 38 },
            { district_id: 404, name: 'Huyện Nông Cống', type: 'Huyện', province_id: 38 },
            { district_id: 405, name: 'Huyện Đông Sơn', type: 'Huyện', province_id: 38 },
            { district_id: 406, name: 'Huyện Quảng Xương', type: 'Huyện', province_id: 38 },
            { district_id: 407, name: 'Huyện Tĩnh Gia', type: 'Huyện', province_id: 38 },
            { district_id: 412, name: 'Thành phố Vinh', type: 'Thành phố', province_id: 40 },
            { district_id: 413, name: 'Thị xã Cửa Lò', type: 'Thị xã', province_id: 40 },
            { district_id: 414, name: 'Thị xã Thái Hoà', type: 'Thị xã', province_id: 40 },
            { district_id: 415, name: 'Huyện Quế Phong', type: 'Huyện', province_id: 40 },
            { district_id: 416, name: 'Huyện Quỳ Châu', type: 'Huyện', province_id: 40 },
            { district_id: 417, name: 'Huyện Kỳ Sơn', type: 'Huyện', province_id: 40 },
            { district_id: 418, name: 'Huyện Tương Dương', type: 'Huyện', province_id: 40 },
            { district_id: 419, name: 'Huyện Nghĩa Đàn', type: 'Huyện', province_id: 40 },
            { district_id: 420, name: 'Huyện Quỳ Hợp', type: 'Huyện', province_id: 40 },
            { district_id: 421, name: 'Huyện Quỳnh Lưu', type: 'Huyện', province_id: 40 },
            { district_id: 422, name: 'Huyện Con Cuông', type: 'Huyện', province_id: 40 },
            { district_id: 423, name: 'Huyện Tân Kỳ', type: 'Huyện', province_id: 40 },
            { district_id: 424, name: 'Huyện Anh Sơn', type: 'Huyện', province_id: 40 },
            { district_id: 425, name: 'Huyện Diễn Châu', type: 'Huyện', province_id: 40 },
            { district_id: 426, name: 'Huyện Yên Thành', type: 'Huyện', province_id: 40 },
            { district_id: 427, name: 'Huyện Đô Lương', type: 'Huyện', province_id: 40 },
            { district_id: 428, name: 'Huyện Thanh Chương', type: 'Huyện', province_id: 40 },
            { district_id: 429, name: 'Huyện Nghi Lộc', type: 'Huyện', province_id: 40 },
            { district_id: 430, name: 'Huyện Nam Đàn', type: 'Huyện', province_id: 40 },
            { district_id: 431, name: 'Huyện Hưng Nguyên', type: 'Huyện', province_id: 40 },
            { district_id: 432, name: 'Thị xã Hoàng Mai', type: 'Thị xã', province_id: 40 },
            {
                district_id: 436,
                name: 'Thành phố Hà Tĩnh',
                type: 'Thành phố',
                province_id: 42,
            },
            { district_id: 437, name: 'Thị xã Hồng Lĩnh', type: 'Thị xã', province_id: 42 },
            { district_id: 439, name: 'Huyện Hương Sơn', type: 'Huyện', province_id: 42 },
            { district_id: 440, name: 'Huyện Đức Thọ', type: 'Huyện', province_id: 42 },
            { district_id: 441, name: 'Huyện Vũ Quang', type: 'Huyện', province_id: 42 },
            { district_id: 442, name: 'Huyện Nghi Xuân', type: 'Huyện', province_id: 42 },
            { district_id: 443, name: 'Huyện Can Lộc', type: 'Huyện', province_id: 42 },
            { district_id: 444, name: 'Huyện Hương Khê', type: 'Huyện', province_id: 42 },
            { district_id: 445, name: 'Huyện Thạch Hà', type: 'Huyện', province_id: 42 },
            { district_id: 446, name: 'Huyện Cẩm Xuyên', type: 'Huyện', province_id: 42 },
            { district_id: 447, name: 'Huyện Kỳ Anh', type: 'Huyện', province_id: 42 },
            { district_id: 448, name: 'Huyện Lộc Hà', type: 'Huyện', province_id: 42 },
            { district_id: 449, name: 'Thị xã Kỳ Anh', type: 'Thị xã', province_id: 42 },
            {
                district_id: 450,
                name: 'Thành Phố Đồng Hới',
                type: 'Thành phố',
                province_id: 44,
            },
            { district_id: 452, name: 'Huyện Minh Hóa', type: 'Huyện', province_id: 44 },
            { district_id: 453, name: 'Huyện Tuyên Hóa', type: 'Huyện', province_id: 44 },
            { district_id: 454, name: 'Huyện Quảng Trạch', type: 'Thị xã', province_id: 44 },
            { district_id: 455, name: 'Huyện Bố Trạch', type: 'Huyện', province_id: 44 },
            { district_id: 456, name: 'Huyện Quảng Ninh', type: 'Huyện', province_id: 44 },
            { district_id: 457, name: 'Huyện Lệ Thủy', type: 'Huyện', province_id: 44 },
            { district_id: 458, name: 'Thị xã Ba Đồn', type: 'Huyện', province_id: 44 },
            {
                district_id: 461,
                name: 'Thành phố Đông Hà',
                type: 'Thành phố',
                province_id: 45,
            },
            { district_id: 462, name: 'Thị xã Quảng Trị', type: 'Thị xã', province_id: 45 },
            { district_id: 464, name: 'Huyện Vĩnh Linh', type: 'Huyện', province_id: 45 },
            { district_id: 465, name: 'Huyện Hướng Hóa', type: 'Huyện', province_id: 45 },
            { district_id: 466, name: 'Huyện Gio Linh', type: 'Huyện', province_id: 45 },
            { district_id: 467, name: 'Huyện Đa Krông', type: 'Huyện', province_id: 45 },
            { district_id: 468, name: 'Huyện Cam Lộ', type: 'Huyện', province_id: 45 },
            { district_id: 469, name: 'Huyện Triệu Phong', type: 'Huyện', province_id: 45 },
            { district_id: 470, name: 'Huyện Hải Lăng', type: 'Huyện', province_id: 45 },
            { district_id: 471, name: 'Huyện Cồn Cỏ', type: 'Huyện', province_id: 45 },
            { district_id: 474, name: 'Thành phố Huế', type: 'Thành phố', province_id: 46 },
            { district_id: 476, name: 'Huyện Phong Điền', type: 'Huyện', province_id: 46 },
            { district_id: 477, name: 'Huyện Quảng Điền', type: 'Huyện', province_id: 46 },
            { district_id: 478, name: 'Huyện Phú Vang', type: 'Huyện', province_id: 46 },
            { district_id: 479, name: 'Thị xã Hương Thủy', type: 'Thị xã', province_id: 46 },
            { district_id: 480, name: 'Thị xã Hương Trà', type: 'Thị xã', province_id: 46 },
            { district_id: 481, name: 'Huyện A Lưới', type: 'Huyện', province_id: 46 },
            { district_id: 482, name: 'Huyện Phú Lộc', type: 'Huyện', province_id: 46 },
            { district_id: 483, name: 'Huyện Nam Đông', type: 'Huyện', province_id: 46 },
            { district_id: 490, name: 'Quận Liên Chiểu', type: 'Quận', province_id: 48 },
            { district_id: 491, name: 'Quận Thanh Khê', type: 'Quận', province_id: 48 },
            { district_id: 492, name: 'Quận Hải Châu', type: 'Quận', province_id: 48 },
            { district_id: 493, name: 'Quận Sơn Trà', type: 'Quận', province_id: 48 },
            { district_id: 494, name: 'Quận Ngũ Hành Sơn', type: 'Quận', province_id: 48 },
            { district_id: 495, name: 'Quận Cẩm Lệ', type: 'Quận', province_id: 48 },
            { district_id: 497, name: 'Huyện Hòa Vang', type: 'Huyện', province_id: 48 },
            { district_id: 498, name: 'Huyện Hoàng Sa', type: 'Huyện', province_id: 48 },
            { district_id: 502, name: 'Thành phố Tam Kỳ', type: 'Thành phố', province_id: 49 },
            { district_id: 503, name: 'Thành phố Hội An', type: 'Thành phố', province_id: 49 },
            { district_id: 504, name: 'Huyện Tây Giang', type: 'Huyện', province_id: 49 },
            { district_id: 505, name: 'Huyện Đông Giang', type: 'Huyện', province_id: 49 },
            { district_id: 506, name: 'Huyện Đại Lộc', type: 'Huyện', province_id: 49 },
            { district_id: 507, name: 'Thị xã Điện Bàn', type: 'Thị xã', province_id: 49 },
            { district_id: 508, name: 'Huyện Duy Xuyên', type: 'Huyện', province_id: 49 },
            { district_id: 509, name: 'Huyện Quế Sơn', type: 'Huyện', province_id: 49 },
            { district_id: 510, name: 'Huyện Nam Giang', type: 'Huyện', province_id: 49 },
            { district_id: 511, name: 'Huyện Phước Sơn', type: 'Huyện', province_id: 49 },
            { district_id: 512, name: 'Huyện Hiệp Đức', type: 'Huyện', province_id: 49 },
            { district_id: 513, name: 'Huyện Thăng Bình', type: 'Huyện', province_id: 49 },
            { district_id: 514, name: 'Huyện Tiên Phước', type: 'Huyện', province_id: 49 },
            { district_id: 515, name: 'Huyện Bắc Trà My', type: 'Huyện', province_id: 49 },
            { district_id: 516, name: 'Huyện Nam Trà My', type: 'Huyện', province_id: 49 },
            { district_id: 517, name: 'Huyện Núi Thành', type: 'Huyện', province_id: 49 },
            { district_id: 518, name: 'Huyện Phú Ninh', type: 'Huyện', province_id: 49 },
            { district_id: 519, name: 'Huyện Nông Sơn', type: 'Huyện', province_id: 49 },
            {
                district_id: 522,
                name: 'Thành phố Quảng Ngãi',
                type: 'Thành phố',
                province_id: 51,
            },
            { district_id: 524, name: 'Huyện Bình Sơn', type: 'Huyện', province_id: 51 },
            { district_id: 525, name: 'Huyện Trà Bồng', type: 'Huyện', province_id: 51 },
            { district_id: 526, name: 'Huyện Tây Trà', type: 'Huyện', province_id: 51 },
            { district_id: 527, name: 'Huyện Sơn Tịnh', type: 'Huyện', province_id: 51 },
            { district_id: 528, name: 'Huyện Tư Nghĩa', type: 'Huyện', province_id: 51 },
            { district_id: 529, name: 'Huyện Sơn Hà', type: 'Huyện', province_id: 51 },
            { district_id: 530, name: 'Huyện Sơn Tây', type: 'Huyện', province_id: 51 },
            { district_id: 531, name: 'Huyện Minh Long', type: 'Huyện', province_id: 51 },
            { district_id: 532, name: 'Huyện Nghĩa Hành', type: 'Huyện', province_id: 51 },
            { district_id: 533, name: 'Huyện Mộ Đức', type: 'Huyện', province_id: 51 },
            { district_id: 534, name: 'Huyện Đức Phổ', type: 'Huyện', province_id: 51 },
            { district_id: 535, name: 'Huyện Ba Tơ', type: 'Huyện', province_id: 51 },
            { district_id: 536, name: 'Huyện Lý Sơn', type: 'Huyện', province_id: 51 },
            {
                district_id: 540,
                name: 'Thành phố Qui Nhơn',
                type: 'Thành phố',
                province_id: 52,
            },
            { district_id: 542, name: 'Huyện An Lão', type: 'Huyện', province_id: 52 },
            { district_id: 543, name: 'Huyện Hoài Nhơn', type: 'Huyện', province_id: 52 },
            { district_id: 544, name: 'Huyện Hoài Ân', type: 'Huyện', province_id: 52 },
            { district_id: 545, name: 'Huyện Phù Mỹ', type: 'Huyện', province_id: 52 },
            { district_id: 546, name: 'Huyện Vĩnh Thạnh', type: 'Huyện', province_id: 52 },
            { district_id: 547, name: 'Huyện Tây Sơn', type: 'Huyện', province_id: 52 },
            { district_id: 548, name: 'Huyện Phù Cát', type: 'Huyện', province_id: 52 },
            { district_id: 549, name: 'Thị xã An Nhơn', type: 'Thị xã', province_id: 52 },
            { district_id: 550, name: 'Huyện Tuy Phước', type: 'Huyện', province_id: 52 },
            { district_id: 551, name: 'Huyện Vân Canh', type: 'Huyện', province_id: 52 },
            {
                district_id: 555,
                name: 'Thành phố Tuy Hoà',
                type: 'Thành phố',
                province_id: 54,
            },
            { district_id: 557, name: 'Thị xã Sông Cầu', type: 'Thị xã', province_id: 54 },
            { district_id: 558, name: 'Huyện Đồng Xuân', type: 'Huyện', province_id: 54 },
            { district_id: 559, name: 'Huyện Tuy An', type: 'Huyện', province_id: 54 },
            { district_id: 560, name: 'Huyện Sơn Hòa', type: 'Huyện', province_id: 54 },
            { district_id: 561, name: 'Huyện Sông Hinh', type: 'Huyện', province_id: 54 },
            { district_id: 562, name: 'Huyện Tây Hoà', type: 'Huyện', province_id: 54 },
            { district_id: 563, name: 'Huyện Phú Hoà', type: 'Huyện', province_id: 54 },
            { district_id: 564, name: 'Huyện Đông Hòa', type: 'Huyện', province_id: 54 },
            {
                district_id: 568,
                name: 'Thành phố Nha Trang',
                type: 'Thành phố',
                province_id: 56,
            },
            {
                district_id: 569,
                name: 'Thành phố Cam Ranh',
                type: 'Thành phố',
                province_id: 56,
            },
            { district_id: 570, name: 'Huyện Cam Lâm', type: 'Huyện', province_id: 56 },
            { district_id: 571, name: 'Huyện Vạn Ninh', type: 'Huyện', province_id: 56 },
            { district_id: 572, name: 'Thị xã Ninh Hòa', type: 'Thị xã', province_id: 56 },
            { district_id: 573, name: 'Huyện Khánh Vĩnh', type: 'Huyện', province_id: 56 },
            { district_id: 574, name: 'Huyện Diên Khánh', type: 'Huyện', province_id: 56 },
            { district_id: 575, name: 'Huyện Khánh Sơn', type: 'Huyện', province_id: 56 },
            { district_id: 576, name: 'Huyện Trường Sa', type: 'Huyện', province_id: 56 },
            {
                district_id: 582,
                name: 'Thành phố Phan Rang-Tháp Chàm',
                type: 'Thành phố',
                province_id: 58,
            },
            { district_id: 584, name: 'Huyện Bác Ái', type: 'Huyện', province_id: 58 },
            { district_id: 585, name: 'Huyện Ninh Sơn', type: 'Huyện', province_id: 58 },
            { district_id: 586, name: 'Huyện Ninh Hải', type: 'Huyện', province_id: 58 },
            { district_id: 587, name: 'Huyện Ninh Phước', type: 'Huyện', province_id: 58 },
            { district_id: 588, name: 'Huyện Thuận Bắc', type: 'Huyện', province_id: 58 },
            { district_id: 589, name: 'Huyện Thuận Nam', type: 'Huyện', province_id: 58 },
            {
                district_id: 593,
                name: 'Thành phố Phan Thiết',
                type: 'Thành phố',
                province_id: 60,
            },
            { district_id: 594, name: 'Thị xã La Gi', type: 'Thị xã', province_id: 60 },
            { district_id: 595, name: 'Huyện Tuy Phong', type: 'Huyện', province_id: 60 },
            { district_id: 596, name: 'Huyện Bắc Bình', type: 'Huyện', province_id: 60 },
            { district_id: 597, name: 'Huyện Hàm Thuận Bắc', type: 'Huyện', province_id: 60 },
            { district_id: 598, name: 'Huyện Hàm Thuận Nam', type: 'Huyện', province_id: 60 },
            { district_id: 599, name: 'Huyện Tánh Linh', type: 'Huyện', province_id: 60 },
            { district_id: 600, name: 'Huyện Đức Linh', type: 'Huyện', province_id: 60 },
            { district_id: 601, name: 'Huyện Hàm Tân', type: 'Huyện', province_id: 60 },
            { district_id: 602, name: 'Huyện Phú Quí', type: 'Huyện', province_id: 60 },
            {
                district_id: 608,
                name: 'Thành phố Kon Tum',
                type: 'Thành phố',
                province_id: 62,
            },
            { district_id: 610, name: 'Huyện Đắk Glei', type: 'Huyện', province_id: 62 },
            { district_id: 611, name: 'Huyện Ngọc Hồi', type: 'Huyện', province_id: 62 },
            { district_id: 612, name: 'Huyện Đắk Tô', type: 'Huyện', province_id: 62 },
            { district_id: 613, name: 'Huyện Kon Plông', type: 'Huyện', province_id: 62 },
            { district_id: 614, name: 'Huyện Kon Rẫy', type: 'Huyện', province_id: 62 },
            { district_id: 615, name: 'Huyện Đắk Hà', type: 'Huyện', province_id: 62 },
            { district_id: 616, name: 'Huyện Sa Thầy', type: 'Huyện', province_id: 62 },
            { district_id: 617, name: 'Huyện Tu Mơ Rông', type: 'Huyện', province_id: 62 },
            { district_id: 618, name: "Huyện Ia H' Drai", type: 'Huyện', province_id: 62 },
            { district_id: 622, name: 'Thành phố Pleiku', type: 'Thành phố', province_id: 64 },
            { district_id: 623, name: 'Thị xã An Khê', type: 'Thị xã', province_id: 64 },
            { district_id: 624, name: 'Thị xã Ayun Pa', type: 'Thị xã', province_id: 64 },
            { district_id: 625, name: 'Huyện KBang', type: 'Huyện', province_id: 64 },
            { district_id: 626, name: 'Huyện Đăk Đoa', type: 'Huyện', province_id: 64 },
            { district_id: 627, name: 'Huyện Chư Păh', type: 'Huyện', province_id: 64 },
            { district_id: 628, name: 'Huyện Ia Grai', type: 'Huyện', province_id: 64 },
            { district_id: 629, name: 'Huyện Mang Yang', type: 'Huyện', province_id: 64 },
            { district_id: 630, name: 'Huyện Kông Chro', type: 'Huyện', province_id: 64 },
            { district_id: 631, name: 'Huyện Đức Cơ', type: 'Huyện', province_id: 64 },
            { district_id: 632, name: 'Huyện Chư Prông', type: 'Huyện', province_id: 64 },
            { district_id: 633, name: 'Huyện Chư Sê', type: 'Huyện', province_id: 64 },
            { district_id: 634, name: 'Huyện Đăk Pơ', type: 'Huyện', province_id: 64 },
            { district_id: 635, name: 'Huyện Ia Pa', type: 'Huyện', province_id: 64 },
            { district_id: 637, name: 'Huyện Krông Pa', type: 'Huyện', province_id: 64 },
            { district_id: 638, name: 'Huyện Phú Thiện', type: 'Huyện', province_id: 64 },
            { district_id: 639, name: 'Huyện Chư Pưh', type: 'Huyện', province_id: 64 },
            {
                district_id: 643,
                name: 'Thành phố Buôn Ma Thuột',
                type: 'Thành phố',
                province_id: 66,
            },
            { district_id: 644, name: 'Thị Xã Buôn Hồ', type: 'Thị xã', province_id: 66 },
            { district_id: 645, name: "Huyện Ea H'leo", type: 'Huyện', province_id: 66 },
            { district_id: 646, name: 'Huyện Ea Súp', type: 'Huyện', province_id: 66 },
            { district_id: 647, name: 'Huyện Buôn Đôn', type: 'Huyện', province_id: 66 },
            { district_id: 648, name: "Huyện Cư M'gar", type: 'Huyện', province_id: 66 },
            { district_id: 649, name: 'Huyện Krông Búk', type: 'Huyện', province_id: 66 },
            { district_id: 650, name: 'Huyện Krông Năng', type: 'Huyện', province_id: 66 },
            { district_id: 651, name: 'Huyện Ea Kar', type: 'Huyện', province_id: 66 },
            { district_id: 652, name: "Huyện M'Đrắk", type: 'Huyện', province_id: 66 },
            { district_id: 653, name: 'Huyện Krông Bông', type: 'Huyện', province_id: 66 },
            { district_id: 654, name: 'Huyện Krông Pắc', type: 'Huyện', province_id: 66 },
            { district_id: 655, name: 'Huyện Krông A Na', type: 'Huyện', province_id: 66 },
            { district_id: 656, name: 'Huyện Lắk', type: 'Huyện', province_id: 66 },
            { district_id: 657, name: 'Huyện Cư Kuin', type: 'Huyện', province_id: 66 },
            { district_id: 660, name: 'Thị xã Gia Nghĩa', type: 'Thị xã', province_id: 67 },
            { district_id: 661, name: 'Huyện Đăk Glong', type: 'Huyện', province_id: 67 },
            { district_id: 662, name: 'Huyện Cư Jút', type: 'Huyện', province_id: 67 },
            { district_id: 663, name: 'Huyện Đắk Mil', type: 'Huyện', province_id: 67 },
            { district_id: 664, name: 'Huyện Krông Nô', type: 'Huyện', province_id: 67 },
            { district_id: 665, name: 'Huyện Đắk Song', type: 'Huyện', province_id: 67 },
            { district_id: 666, name: 'Huyện Đắk R Lấp', type: 'Huyện', province_id: 67 },
            { district_id: 667, name: 'Huyện Tuy Đức', type: 'Huyện', province_id: 67 },
            { district_id: 672, name: 'Thành phố Đà Lạt', type: 'Thành phố', province_id: 68 },
            {
                district_id: 673,
                name: 'Thành phố Bảo Lộc',
                type: 'Thành phố',
                province_id: 68,
            },
            { district_id: 674, name: 'Huyện Đam Rông', type: 'Huyện', province_id: 68 },
            { district_id: 675, name: 'Huyện Lạc Dương', type: 'Huyện', province_id: 68 },
            { district_id: 676, name: 'Huyện Lâm Hà', type: 'Huyện', province_id: 68 },
            { district_id: 677, name: 'Huyện Đơn Dương', type: 'Huyện', province_id: 68 },
            { district_id: 678, name: 'Huyện Đức Trọng', type: 'Huyện', province_id: 68 },
            { district_id: 679, name: 'Huyện Di Linh', type: 'Huyện', province_id: 68 },
            { district_id: 680, name: 'Huyện Bảo Lâm', type: 'Huyện', province_id: 68 },
            { district_id: 681, name: 'Huyện Đạ Huoai', type: 'Huyện', province_id: 68 },
            { district_id: 682, name: 'Huyện Đạ Tẻh', type: 'Huyện', province_id: 68 },
            { district_id: 683, name: 'Huyện Cát Tiên', type: 'Huyện', province_id: 68 },
            { district_id: 688, name: 'Thị xã Phước Long', type: 'Thị xã', province_id: 70 },
            { district_id: 689, name: 'Thị xã Đồng Xoài', type: 'Thị xã', province_id: 70 },
            { district_id: 690, name: 'Thị xã Bình Long', type: 'Thị xã', province_id: 70 },
            { district_id: 691, name: 'Huyện Bù Gia Mập', type: 'Huyện', province_id: 70 },
            { district_id: 692, name: 'Huyện Lộc Ninh', type: 'Huyện', province_id: 70 },
            { district_id: 693, name: 'Huyện Bù Đốp', type: 'Huyện', province_id: 70 },
            { district_id: 694, name: 'Huyện Hớn Quản', type: 'Huyện', province_id: 70 },
            { district_id: 695, name: 'Huyện Đồng Phú', type: 'Huyện', province_id: 70 },
            { district_id: 696, name: 'Huyện Bù Đăng', type: 'Huyện', province_id: 70 },
            { district_id: 697, name: 'Huyện Chơn Thành', type: 'Huyện', province_id: 70 },
            { district_id: 698, name: 'Huyện Phú Riềng', type: 'Huyện', province_id: 70 },
            {
                district_id: 703,
                name: 'Thành phố Tây Ninh',
                type: 'Thành phố',
                province_id: 72,
            },
            { district_id: 705, name: 'Huyện Tân Biên', type: 'Huyện', province_id: 72 },
            { district_id: 706, name: 'Huyện Tân Châu', type: 'Huyện', province_id: 72 },
            {
                district_id: 707,
                name: 'Huyện Dương Minh Châu',
                type: 'Huyện',
                province_id: 72,
            },
            { district_id: 708, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 72 },
            { district_id: 709, name: 'Huyện Hòa Thành', type: 'Huyện', province_id: 72 },
            { district_id: 710, name: 'Huyện Gò Dầu', type: 'Huyện', province_id: 72 },
            { district_id: 711, name: 'Huyện Bến Cầu', type: 'Huyện', province_id: 72 },
            { district_id: 712, name: 'Huyện Trảng Bàng', type: 'Huyện', province_id: 72 },
            {
                district_id: 718,
                name: 'Thành phố Thủ Dầu Một',
                type: 'Thành phố',
                province_id: 74,
            },
            { district_id: 719, name: 'Huyện Bàu Bàng', type: 'Huyện', province_id: 74 },
            { district_id: 720, name: 'Huyện Dầu Tiếng', type: 'Huyện', province_id: 74 },
            { district_id: 721, name: 'Thị xã Bến Cát', type: 'Thị xã', province_id: 74 },
            { district_id: 722, name: 'Huyện Phú Giáo', type: 'Huyện', province_id: 74 },
            { district_id: 723, name: 'Thị xã Tân Uyên', type: 'Thị xã', province_id: 74 },
            { district_id: 724, name: 'Thị xã Dĩ An', type: 'Thị xã', province_id: 74 },
            { district_id: 725, name: 'Thị xã Thuận An', type: 'Thị xã', province_id: 74 },
            { district_id: 726, name: 'Huyện Bắc Tân Uyên', type: 'Huyện', province_id: 74 },
            {
                district_id: 731,
                name: 'Thành phố Biên Hòa',
                type: 'Thành phố',
                province_id: 75,
            },
            { district_id: 732, name: 'Thị xã Long Khánh', type: 'Thị xã', province_id: 75 },
            { district_id: 734, name: 'Huyện Tân Phú', type: 'Huyện', province_id: 75 },
            { district_id: 735, name: 'Huyện Vĩnh Cửu', type: 'Huyện', province_id: 75 },
            { district_id: 736, name: 'Huyện Định Quán', type: 'Huyện', province_id: 75 },
            { district_id: 737, name: 'Huyện Trảng Bom', type: 'Huyện', province_id: 75 },
            { district_id: 738, name: 'Huyện Thống Nhất', type: 'Huyện', province_id: 75 },
            { district_id: 739, name: 'Huyện Cẩm Mỹ', type: 'Huyện', province_id: 75 },
            { district_id: 740, name: 'Huyện Long Thành', type: 'Huyện', province_id: 75 },
            { district_id: 741, name: 'Huyện Xuân Lộc', type: 'Huyện', province_id: 75 },
            { district_id: 742, name: 'Huyện Nhơn Trạch', type: 'Huyện', province_id: 75 },
            {
                district_id: 747,
                name: 'Thành phố Vũng Tàu',
                type: 'Thành phố',
                province_id: 77,
            },
            { district_id: 748, name: 'Thành phố Bà Rịa', type: 'Thành phố', province_id: 77 },
            { district_id: 750, name: 'Huyện Châu Đức', type: 'Huyện', province_id: 77 },
            { district_id: 751, name: 'Huyện Xuyên Mộc', type: 'Huyện', province_id: 77 },
            { district_id: 752, name: 'Huyện Long Điền', type: 'Huyện', province_id: 77 },
            { district_id: 753, name: 'Huyện Đất Đỏ', type: 'Huyện', province_id: 77 },
            { district_id: 754, name: 'Huyện Tân Thành', type: 'Huyện', province_id: 77 },
            { district_id: 755, name: 'Huyện Côn Đảo', type: 'Huyện', province_id: 77 },
            { district_id: 760, name: 'Quận 1', type: 'Quận', province_id: 79 },
            { district_id: 761, name: 'Quận 12', type: 'Quận', province_id: 79 },
            { district_id: 762, name: 'Quận Thủ Đức', type: 'Quận', province_id: 79 },
            { district_id: 763, name: 'Quận 9', type: 'Quận', province_id: 79 },
            { district_id: 764, name: 'Quận Gò Vấp', type: 'Quận', province_id: 79 },
            { district_id: 765, name: 'Quận Bình Thạnh', type: 'Quận', province_id: 79 },
            { district_id: 766, name: 'Quận Tân Bình', type: 'Quận', province_id: 79 },
            { district_id: 767, name: 'Quận Tân Phú', type: 'Quận', province_id: 79 },
            { district_id: 768, name: 'Quận Phú Nhuận', type: 'Quận', province_id: 79 },
            { district_id: 769, name: 'Quận 2', type: 'Quận', province_id: 79 },
            { district_id: 770, name: 'Quận 3', type: 'Quận', province_id: 79 },
            { district_id: 771, name: 'Quận 10', type: 'Quận', province_id: 79 },
            { district_id: 772, name: 'Quận 11', type: 'Quận', province_id: 79 },
            { district_id: 773, name: 'Quận 4', type: 'Quận', province_id: 79 },
            { district_id: 774, name: 'Quận 5', type: 'Quận', province_id: 79 },
            { district_id: 775, name: 'Quận 6', type: 'Quận', province_id: 79 },
            { district_id: 776, name: 'Quận 8', type: 'Quận', province_id: 79 },
            { district_id: 777, name: 'Quận Bình Tân', type: 'Quận', province_id: 79 },
            { district_id: 778, name: 'Quận 7', type: 'Quận', province_id: 79 },
            { district_id: 783, name: 'Huyện Củ Chi', type: 'Huyện', province_id: 79 },
            { district_id: 784, name: 'Huyện Hóc Môn', type: 'Huyện', province_id: 79 },
            { district_id: 785, name: 'Huyện Bình Chánh', type: 'Huyện', province_id: 79 },
            { district_id: 786, name: 'Huyện Nhà Bè', type: 'Huyện', province_id: 79 },
            { district_id: 787, name: 'Huyện Cần Giờ', type: 'Huyện', province_id: 79 },
            { district_id: 794, name: 'Thành phố Tân An', type: 'Thành phố', province_id: 80 },
            { district_id: 795, name: 'Thị xã Kiến Tường', type: 'Thị xã', province_id: 80 },
            { district_id: 796, name: 'Huyện Tân Hưng', type: 'Huyện', province_id: 80 },
            { district_id: 797, name: 'Huyện Vĩnh Hưng', type: 'Huyện', province_id: 80 },
            { district_id: 798, name: 'Huyện Mộc Hóa', type: 'Huyện', province_id: 80 },
            { district_id: 799, name: 'Huyện Tân Thạnh', type: 'Huyện', province_id: 80 },
            { district_id: 800, name: 'Huyện Thạnh Hóa', type: 'Huyện', province_id: 80 },
            { district_id: 801, name: 'Huyện Đức Huệ', type: 'Huyện', province_id: 80 },
            { district_id: 802, name: 'Huyện Đức Hòa', type: 'Huyện', province_id: 80 },
            { district_id: 803, name: 'Huyện Bến Lức', type: 'Huyện', province_id: 80 },
            { district_id: 804, name: 'Huyện Thủ Thừa', type: 'Huyện', province_id: 80 },
            { district_id: 805, name: 'Huyện Tân Trụ', type: 'Huyện', province_id: 80 },
            { district_id: 806, name: 'Huyện Cần Đước', type: 'Huyện', province_id: 80 },
            { district_id: 807, name: 'Huyện Cần Giuộc', type: 'Huyện', province_id: 80 },
            { district_id: 808, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 80 },
            { district_id: 815, name: 'Thành phố Mỹ Tho', type: 'Thành phố', province_id: 82 },
            { district_id: 816, name: 'Thị xã Gò Công', type: 'Thị xã', province_id: 82 },
            { district_id: 817, name: 'Thị xã Cai Lậy', type: 'Huyện', province_id: 82 },
            { district_id: 818, name: 'Huyện Tân Phước', type: 'Huyện', province_id: 82 },
            { district_id: 819, name: 'Huyện Cái Bè', type: 'Huyện', province_id: 82 },
            { district_id: 820, name: 'Huyện Cai Lậy', type: 'Thị xã', province_id: 82 },
            { district_id: 821, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 82 },
            { district_id: 822, name: 'Huyện Chợ Gạo', type: 'Huyện', province_id: 82 },
            { district_id: 823, name: 'Huyện Gò Công Tây', type: 'Huyện', province_id: 82 },
            { district_id: 824, name: 'Huyện Gò Công Đông', type: 'Huyện', province_id: 82 },
            { district_id: 825, name: 'Huyện Tân Phú Đông', type: 'Huyện', province_id: 82 },
            {
                district_id: 829,
                name: 'Thành phố Bến Tre',
                type: 'Thành phố',
                province_id: 83,
            },
            { district_id: 831, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 83 },
            { district_id: 832, name: 'Huyện Chợ Lách', type: 'Huyện', province_id: 83 },
            { district_id: 833, name: 'Huyện Mỏ Cày Nam', type: 'Huyện', province_id: 83 },
            { district_id: 834, name: 'Huyện Giồng Trôm', type: 'Huyện', province_id: 83 },
            { district_id: 835, name: 'Huyện Bình Đại', type: 'Huyện', province_id: 83 },
            { district_id: 836, name: 'Huyện Ba Tri', type: 'Huyện', province_id: 83 },
            { district_id: 837, name: 'Huyện Thạnh Phú', type: 'Huyện', province_id: 83 },
            { district_id: 838, name: 'Huyện Mỏ Cày Bắc', type: 'Huyện', province_id: 83 },
            {
                district_id: 842,
                name: 'Thành phố Trà Vinh',
                type: 'Thành phố',
                province_id: 84,
            },
            { district_id: 844, name: 'Huyện Càng Long', type: 'Huyện', province_id: 84 },
            { district_id: 845, name: 'Huyện Cầu Kè', type: 'Huyện', province_id: 84 },
            { district_id: 846, name: 'Huyện Tiểu Cần', type: 'Huyện', province_id: 84 },
            { district_id: 847, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 84 },
            { district_id: 848, name: 'Huyện Cầu Ngang', type: 'Huyện', province_id: 84 },
            { district_id: 849, name: 'Huyện Trà Cú', type: 'Huyện', province_id: 84 },
            { district_id: 850, name: 'Huyện Duyên Hải', type: 'Huyện', province_id: 84 },
            { district_id: 851, name: 'Thị xã Duyên Hải', type: 'Thị xã', province_id: 84 },
            {
                district_id: 855,
                name: 'Thành phố Vĩnh Long',
                type: 'Thành phố',
                province_id: 86,
            },
            { district_id: 857, name: 'Huyện Long Hồ', type: 'Huyện', province_id: 86 },
            { district_id: 858, name: 'Huyện Mang Thít', type: 'Huyện', province_id: 86 },
            { district_id: 859, name: 'Huyện  Vũng Liêm', type: 'Huyện', province_id: 86 },
            { district_id: 860, name: 'Huyện Tam Bình', type: 'Huyện', province_id: 86 },
            { district_id: 861, name: 'Thị xã Bình Minh', type: 'Thị xã', province_id: 86 },
            { district_id: 862, name: 'Huyện Trà Ôn', type: 'Huyện', province_id: 86 },
            { district_id: 863, name: 'Huyện Bình Tân', type: 'Huyện', province_id: 86 },
            {
                district_id: 866,
                name: 'Thành phố Cao Lãnh',
                type: 'Thành phố',
                province_id: 87,
            },
            { district_id: 867, name: 'Thành phố Sa Đéc', type: 'Thành phố', province_id: 87 },
            { district_id: 868, name: 'Thị xã Hồng Ngự', type: 'Thị xã', province_id: 87 },
            { district_id: 869, name: 'Huyện Tân Hồng', type: 'Huyện', province_id: 87 },
            { district_id: 870, name: 'Huyện Hồng Ngự', type: 'Huyện', province_id: 87 },
            { district_id: 871, name: 'Huyện Tam Nông', type: 'Huyện', province_id: 87 },
            { district_id: 872, name: 'Huyện Tháp Mười', type: 'Huyện', province_id: 87 },
            { district_id: 873, name: 'Huyện Cao Lãnh', type: 'Huyện', province_id: 87 },
            { district_id: 874, name: 'Huyện Thanh Bình', type: 'Huyện', province_id: 87 },
            { district_id: 875, name: 'Huyện Lấp Vò', type: 'Huyện', province_id: 87 },
            { district_id: 876, name: 'Huyện Lai Vung', type: 'Huyện', province_id: 87 },
            { district_id: 877, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 87 },
            {
                district_id: 883,
                name: 'Thành phố Long Xuyên',
                type: 'Thành phố',
                province_id: 89,
            },
            {
                district_id: 884,
                name: 'Thành phố Châu Đốc',
                type: 'Thành phố',
                province_id: 89,
            },
            { district_id: 886, name: 'Huyện An Phú', type: 'Huyện', province_id: 89 },
            { district_id: 887, name: 'Thị xã Tân Châu', type: 'Thị xã', province_id: 89 },
            { district_id: 888, name: 'Huyện Phú Tân', type: 'Huyện', province_id: 89 },
            { district_id: 889, name: 'Huyện Châu Phú', type: 'Huyện', province_id: 89 },
            { district_id: 890, name: 'Huyện Tịnh Biên', type: 'Huyện', province_id: 89 },
            { district_id: 891, name: 'Huyện Tri Tôn', type: 'Huyện', province_id: 89 },
            { district_id: 892, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 89 },
            { district_id: 893, name: 'Huyện Chợ Mới', type: 'Huyện', province_id: 89 },
            { district_id: 894, name: 'Huyện Thoại Sơn', type: 'Huyện', province_id: 89 },
            {
                district_id: 899,
                name: 'Thành phố Rạch Giá',
                type: 'Thành phố',
                province_id: 91,
            },
            { district_id: 900, name: 'Thị xã Hà Tiên', type: 'Thị xã', province_id: 91 },
            { district_id: 902, name: 'Huyện Kiên Lương', type: 'Huyện', province_id: 91 },
            { district_id: 903, name: 'Huyện Hòn Đất', type: 'Huyện', province_id: 91 },
            { district_id: 904, name: 'Huyện Tân Hiệp', type: 'Huyện', province_id: 91 },
            { district_id: 905, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 91 },
            { district_id: 906, name: 'Huyện Giồng Riềng', type: 'Huyện', province_id: 91 },
            { district_id: 907, name: 'Huyện Gò Quao', type: 'Huyện', province_id: 91 },
            { district_id: 908, name: 'Huyện An Biên', type: 'Huyện', province_id: 91 },
            { district_id: 909, name: 'Huyện An Minh', type: 'Huyện', province_id: 91 },
            { district_id: 910, name: 'Huyện Vĩnh Thuận', type: 'Huyện', province_id: 91 },
            { district_id: 911, name: 'Huyện Phú Quốc', type: 'Huyện', province_id: 91 },
            { district_id: 912, name: 'Huyện Kiên Hải', type: 'Huyện', province_id: 91 },
            { district_id: 913, name: 'Huyện U Minh Thượng', type: 'Huyện', province_id: 91 },
            { district_id: 914, name: 'Huyện Giang Thành', type: 'Huyện', province_id: 91 },
            { district_id: 916, name: 'Quận Ninh Kiều', type: 'Quận', province_id: 92 },
            { district_id: 917, name: 'Quận Ô Môn', type: 'Quận', province_id: 92 },
            { district_id: 918, name: 'Quận Bình Thuỷ', type: 'Quận', province_id: 92 },
            { district_id: 919, name: 'Quận Cái Răng', type: 'Quận', province_id: 92 },
            { district_id: 923, name: 'Quận Thốt Nốt', type: 'Quận', province_id: 92 },
            { district_id: 924, name: 'Huyện Vĩnh Thạnh', type: 'Huyện', province_id: 92 },
            { district_id: 925, name: 'Huyện Cờ Đỏ', type: 'Huyện', province_id: 92 },
            { district_id: 926, name: 'Huyện Phong Điền', type: 'Huyện', province_id: 92 },
            { district_id: 927, name: 'Huyện Thới Lai', type: 'Huyện', province_id: 92 },
            {
                district_id: 930,
                name: 'Thành phố Vị Thanh',
                type: 'Thành phố',
                province_id: 93,
            },
            { district_id: 931, name: 'Thị xã Ngã Bảy', type: 'Thị xã', province_id: 93 },
            { district_id: 932, name: 'Huyện Châu Thành A', type: 'Huyện', province_id: 93 },
            { district_id: 933, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 93 },
            { district_id: 934, name: 'Huyện Phụng Hiệp', type: 'Huyện', province_id: 93 },
            { district_id: 935, name: 'Huyện Vị Thuỷ', type: 'Huyện', province_id: 93 },
            { district_id: 936, name: 'Huyện Long Mỹ', type: 'Huyện', province_id: 93 },
            { district_id: 937, name: 'Thị xã Long Mỹ', type: 'Thị xã', province_id: 93 },
            {
                district_id: 941,
                name: 'Thành phố Sóc Trăng',
                type: 'Thành phố',
                province_id: 94,
            },
            { district_id: 942, name: 'Huyện Châu Thành', type: 'Huyện', province_id: 94 },
            { district_id: 943, name: 'Huyện Kế Sách', type: 'Huyện', province_id: 94 },
            { district_id: 944, name: 'Huyện Mỹ Tú', type: 'Huyện', province_id: 94 },
            { district_id: 945, name: 'Huyện Cù Lao Dung', type: 'Huyện', province_id: 94 },
            { district_id: 946, name: 'Huyện Long Phú', type: 'Huyện', province_id: 94 },
            { district_id: 947, name: 'Huyện Mỹ Xuyên', type: 'Huyện', province_id: 94 },
            { district_id: 948, name: 'Thị xã Ngã Năm', type: 'Thị xã', province_id: 94 },
            { district_id: 949, name: 'Huyện Thạnh Trị', type: 'Huyện', province_id: 94 },
            { district_id: 950, name: 'Thị xã Vĩnh Châu', type: 'Thị xã', province_id: 94 },
            { district_id: 951, name: 'Huyện Trần Đề', type: 'Huyện', province_id: 94 },
            {
                district_id: 954,
                name: 'Thành phố Bạc Liêu',
                type: 'Thành phố',
                province_id: 95,
            },
            { district_id: 956, name: 'Huyện Hồng Dân', type: 'Huyện', province_id: 95 },
            { district_id: 957, name: 'Huyện Phước Long', type: 'Huyện', province_id: 95 },
            { district_id: 958, name: 'Huyện Vĩnh Lợi', type: 'Huyện', province_id: 95 },
            { district_id: 959, name: 'Thị xã Giá Rai', type: 'Thị xã', province_id: 95 },
            { district_id: 960, name: 'Huyện Đông Hải', type: 'Huyện', province_id: 95 },
            { district_id: 961, name: 'Huyện Hoà Bình', type: 'Huyện', province_id: 95 },
            { district_id: 964, name: 'Thành phố Cà Mau', type: 'Thành phố', province_id: 96 },
            { district_id: 966, name: 'Huyện U Minh', type: 'Huyện', province_id: 96 },
            { district_id: 967, name: 'Huyện Thới Bình', type: 'Huyện', province_id: 96 },
            { district_id: 968, name: 'Huyện Trần Văn Thời', type: 'Huyện', province_id: 96 },
            { district_id: 969, name: 'Huyện Cái Nước', type: 'Huyện', province_id: 96 },
            { district_id: 970, name: 'Huyện Đầm Dơi', type: 'Huyện', province_id: 96 },
            { district_id: 971, name: 'Huyện Năm Căn', type: 'Huyện', province_id: 96 },
            { district_id: 972, name: 'Huyện Phú Tân', type: 'Huyện', province_id: 96 },
            { district_id: 973, name: 'Huyện Ngọc Hiển', type: 'Huyện', province_id: 96 },
        ])
    },
    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete('Districts', null, {});
    }
};